-- Generated by `cargo test --test v1_sql_golden`. Do not edit by hand.

-- ── Filters.by_status ──
-- $1 = Status.open :: s.status
-- $2 = Status.paid :: s.status
SELECT coalesce(json_agg(q.j), '[]'::json)::text FROM (SELECT json_build_object('id', t0.id::text, 'org_id', t0.org_id::text, 'status', t0.status) AS j
  FROM s.invoices t0
  WHERE t0.status IN (($1::text)::s.status, ($2::text)::s.status)
  ORDER BY t0.id) q

-- ── Filters.by_statuses ──
-- $1 = @statuses :: s.status[]
SELECT coalesce(json_agg(q.j), '[]'::json)::text FROM (SELECT json_build_object('id', t0.id::text, 'org_id', t0.org_id::text, 'status', t0.status) AS j
  FROM s.invoices t0
  WHERE t0.status = ANY(($1::text)::s.status[])
  ORDER BY t0.id) q

-- ── Filters.not_in ──
-- $1 = @statuses :: s.status[]
SELECT coalesce(json_agg(q.j), '[]'::json)::text FROM (SELECT json_build_object('id', t0.id::text, 'org_id', t0.org_id::text, 'status', t0.status) AS j
  FROM s.invoices t0
  WHERE t0.status <> ALL(($1::text)::s.status[])
  ORDER BY t0.id) q

-- ── Filters.with_open_invoices ──
-- $1 = Status.open :: s.status
SELECT coalesce(json_agg(q.j), '[]'::json)::text FROM (SELECT json_build_object('id', t0.id::text, 'name', t0.name) AS j
  FROM s.orgs t0
  WHERE EXISTS (SELECT 1 FROM s.invoices t1 WHERE (t1.org_id = t0.id) AND (t1.status = ($1::text)::s.status))
  ORDER BY t0.id) q

-- ── Filters.without_invoices ──
SELECT coalesce(json_agg(q.j), '[]'::json)::text FROM (SELECT json_build_object('id', t0.id::text, 'name', t0.name) AS j
  FROM s.orgs t0
  WHERE NOT EXISTS (SELECT 1 FROM s.invoices t1 WHERE t1.org_id = t0.id)
  ORDER BY t0.id) q
