-- Generated by `cargo test --test v1_sql_golden`. Do not edit by hand.

-- ── view InvoiceDetail ──
-- $1 = 50 :: int
SELECT coalesce(json_agg(q.j), '[]'::json)::text FROM (SELECT json_build_object('id', t0.id::text, 'org_id', t0.org_id::text, 'number', t0.number, 'issued_at', t0.issued_at, 'lines', coalesce(t1_agg.data, '[]'::json)) AS j
  FROM s.invoices t0
  LEFT JOIN LATERAL (
      SELECT coalesce(json_agg(c.j), '[]'::json) AS data
        FROM (SELECT json_build_object('id', t1.id::text, 'body', t1.body) AS j
        FROM s.lines t1
        WHERE t1.invoice_id = t0.id
        ORDER BY t1.id
        LIMIT ($1::text)::int) c
  ) t1_agg ON true) q

-- ── Invoices.recent ──
-- $1 = @org_id :: bigint
-- $2 = @size :: int
SELECT coalesce(json_agg(q.j), '[]'::json)::text FROM (WITH page AS MATERIALIZED (
  SELECT p1.id FROM s.invoices p1
   WHERE p1.org_id = ($1::text)::bigint
   ORDER BY p1.issued_at DESC, p1.id DESC
   LIMIT ($2::text)::int
)
SELECT json_build_object('id', t0.id::text, 'org_id', t0.org_id::text, 'number', t0.number, 'issued_at', t0.issued_at, 'lines', t0.lines) AS j
  FROM s.invoice_detail t0
  JOIN page ON page.id = t0.id
  ORDER BY t0.issued_at DESC, t0.id DESC) q

-- ── Invoices.recent_inline ──
-- $1 = @org_id :: bigint
-- $2 = @size :: int
-- $3 = 50 :: int
SELECT coalesce(json_agg(q.j), '[]'::json)::text FROM (WITH page AS MATERIALIZED (
  SELECT p2.id FROM s.invoices p2
   WHERE p2.org_id = ($1::text)::bigint
   ORDER BY p2.issued_at DESC, p2.id DESC
   LIMIT ($2::text)::int
)
SELECT json_build_object('id', t0.id::text, 'number', t0.number, 'issued_at', t0.issued_at, 'lines', coalesce(t1_agg.data, '[]'::json)) AS j
  FROM s.invoices t0
  LEFT JOIN LATERAL (
      SELECT coalesce(json_agg(c.j), '[]'::json) AS data
        FROM (SELECT json_build_object('id', t1.id::text, 'body', t1.body) AS j
        FROM s.lines t1
        WHERE t1.invoice_id = t0.id
        ORDER BY t1.id
        LIMIT ($3::text)::int) c
  ) t1_agg ON true
  JOIN page ON page.id = t0.id
  ORDER BY t0.issued_at DESC, t0.id DESC) q

-- ── Invoices.recent_by_number ──
-- $1 = @org_id :: bigint
-- $2 = @size :: int
SELECT coalesce(json_agg(q.j), '[]'::json)::text FROM (WITH page AS MATERIALIZED (
  SELECT p1.id FROM s.invoices p1
   WHERE p1.org_id = ($1::text)::bigint
   ORDER BY p1.number
   LIMIT ($2::text)::int
)
SELECT json_build_object('id', t0.id::text, 'org_id', t0.org_id::text, 'number', t0.number, 'issued_at', t0.issued_at, 'lines', t0.lines) AS j
  FROM s.invoice_detail t0
  JOIN page ON page.id = t0.id
  ORDER BY t0.number) q

-- ── Invoices.one ──
-- $1 = @invoice_id :: bigint
SELECT q.j::text FROM (SELECT json_build_object('id', t0.id::text, 'org_id', t0.org_id::text, 'number', t0.number, 'issued_at', t0.issued_at, 'lines', t0.lines) AS j
  FROM s.invoice_detail t0
  WHERE t0.id = ($1::text)::bigint
  LIMIT 1) q

-- ── view InvoiceWithOrg ──
-- $1 = 50 :: int
SELECT coalesce(json_agg(q.j), '[]'::json)::text FROM (SELECT json_build_object('id', t0.id::text, 'org_id', t0.org_id::text, 'number', t0.number, 'issued_at', t0.issued_at, 'org', CASE WHEN t1.id IS NULL THEN NULL ELSE json_build_object('id', t1.id::text, 'name', t1.name) END, 'lines', coalesce(t2_agg.data, '[]'::json)) AS j
  FROM s.invoices t0
  LEFT JOIN s.orgs t1 ON t1.id = t0.org_id
  LEFT JOIN LATERAL (
      SELECT coalesce(json_agg(c.j), '[]'::json) AS data
        FROM (SELECT json_build_object('id', t2.id::text, 'body', t2.body) AS j
        FROM s.lines t2
        WHERE t2.invoice_id = t0.id
        ORDER BY t2.id
        LIMIT ($1::text)::int) c
  ) t2_agg ON true) q

-- ── ByOrgName.unbounded ──
-- not compilable yet: this query is not expressible yet
