-- Generated by `cargo test --test v1_sql_golden`. Do not edit by hand.

-- ── Accounts.one ──
-- $1 = $id :: bigint
SELECT q.j::text FROM (SELECT json_build_object('id', t0.id::text, 'email', t0.email) AS j
  FROM s."user" t0
  WHERE t0.id = ($1::text)::bigint
  LIMIT 1) q
