-- Generated by `cargo test --test v1_sql_golden`. Do not edit by hand.

-- ── Notes.by_region ──
-- $1 = @region :: varchar(20)
SELECT coalesce(json_agg(q.j), '[]'::json)::text FROM (SELECT json_build_object('id', t0.id::text, 'body', t0.body) AS j
  FROM s.notes t0
  LEFT JOIN s.orgs t1 ON t1.id = t0.org_id
  WHERE t1.region = ($1::text)::varchar(20)
  ORDER BY t0.id) q

-- ── Notes.by_org_name ──
SELECT coalesce(json_agg(q.j), '[]'::json)::text FROM (SELECT json_build_object('id', t0.id::text) AS j
  FROM s.notes t0
  LEFT JOIN s.orgs t1 ON t1.id = t0.org_id
  ORDER BY t1.name, t0.id) q

-- ── Notes.with_org ──
-- $1 = @region :: varchar(20)
SELECT coalesce(json_agg(q.j), '[]'::json)::text FROM (SELECT json_build_object('id', t0.id::text, 'org', CASE WHEN t1.id IS NULL THEN NULL ELSE json_build_object('id', t1.id::text, 'name', t1.name) END) AS j
  FROM s.notes t0
  LEFT JOIN s.orgs t1 ON t1.id = t0.org_id
  WHERE t1.region = ($1::text)::varchar(20)
  ORDER BY t0.id) q
