-- Generated by `cargo test --test v1_sql_golden`. Do not edit by hand.

-- ── middleware RequireOrgMember ──
-- $1 = @org_id :: bigint
-- $2 = @account_id :: bigint
SELECT q.j::text FROM (SELECT json_build_object('org_id', t0.org_id::text, 'account_id', t0.account_id::text, 'role', t0.role, 'org', t0.org) AS j
  FROM org.member_access t0
  WHERE (t0.org_id = ($1::text)::bigint) AND (t0.account_id = ($2::text)::bigint)
  LIMIT 1) q

-- ── AuthService.login ──
-- $1 = @req.email :: varchar(255)
SELECT q.j::text FROM (SELECT json_build_object('id', t0.id::text, 'password_hash', t0.password_hash) AS j
  FROM auth.accounts t0
  WHERE t0.email = ($1::text)::varchar(255)
  LIMIT 1) q

-- ── AuthService.profile ──
-- $1 = @account_id :: bigint
SELECT q.j::text FROM (SELECT json_build_object('id', t0.id::text, 'email', t0.email, 'display_name', t0.display_name, 'email_verified', t0.email_verified, 'created_at', t0.created_at) AS j
  FROM auth.accounts t0
  WHERE t0.id = ($1::text)::bigint
  LIMIT 1) q

-- ── AuthService.orgs_of ──
-- $1 = @account_id :: bigint
SELECT coalesce(json_agg(q.j), '[]'::json)::text FROM (SELECT json_build_object('org_id', t0.org_id::text, 'account_id', t0.account_id::text, 'role', t0.role, 'org', t0.org) AS j
  FROM org.member_access t0
  WHERE t0.account_id = ($1::text)::bigint
  ORDER BY t0.org__name) q

-- ── BillingService.plans ──
-- $1 = true :: boolean
SELECT coalesce(json_agg(q.j), '[]'::json)::text FROM (SELECT json_build_object('id', t0.id::text, 'code', t0.code, 'name', t0.name, 'price', t0.price::text, 'currency', t0.currency, 'interval', t0.interval, 'features', t0.features) AS j
  FROM billing.plans t0
  WHERE t0.active = ($1::text)::boolean
  ORDER BY t0.price, t0.id) q

-- ── BillingService.subscription ──
-- $1 = @org_id :: bigint
-- $2 = SubscriptionStatus.canceled :: billing.subscription_status
SELECT q.j::text FROM (SELECT json_build_object('id', t0.id::text, 'org_id', t0.org_id::text, 'status', t0.status, 'current_period_start', t0.current_period_start, 'current_period_end', t0.current_period_end, 'cancel_at', t0.cancel_at, 'plan', t0.plan, 'org', t0.org) AS j
  FROM billing.subscription_detail t0
  WHERE (t0.org_id = ($1::text)::bigint) AND (t0.status <> ($2::text)::billing.subscription_status)
  LIMIT 1) q

-- ── BillingService.subscribe ──
-- $1 = @req.plan_code :: varchar(40)
-- $2 = true :: boolean
SELECT q.j::text FROM (SELECT json_build_object('id', t0.id::text, 'interval', t0.interval) AS j
  FROM billing.plans t0
  WHERE (t0.code = ($1::text)::varchar(40)) AND (t0.active = ($2::text)::boolean)
  LIMIT 1) q

-- ── BillingService.invoices ──
-- $1 = @org_id :: bigint
-- $2 = @status :: billing.invoice_status
-- $3 = <cursor.0> :: timestamptz
-- $4 = <cursor.1> :: bigint
-- $5 = @size :: int
SELECT coalesce(json_agg(q.j ORDER BY q.rn) FILTER (WHERE q.rn <= LEAST(GREATEST(($5::text)::int, 1), 100)), '[]'::json)::text, coalesce(json_agg(q.k ORDER BY q.rn) FILTER (WHERE q.rn <= LEAST(GREATEST(($5::text)::int, 1), 100)), '[]'::json)::text, count(*) > LEAST(GREATEST(($5::text)::int, 1), 100) FROM (WITH page AS MATERIALIZED (
  SELECT p1.id FROM billing.invoices p1
   WHERE (p1.org_id = ($1::text)::bigint) AND (($2::text IS NULL OR p1.status = ($2::text)::billing.invoice_status)) AND ($3::text IS NULL OR (p1.issued_at < ($3::text)::timestamptz OR (p1.issued_at = ($3::text)::timestamptz AND (p1.id < ($4::text)::bigint))))
   ORDER BY p1.issued_at DESC, p1.id DESC
   LIMIT (LEAST(GREATEST(($5::text)::int, 1), 100) + 1)
)
SELECT json_build_object('id', t0.id::text, 'org_id', t0.org_id::text, 'number', t0.number, 'amount', t0.amount::text, 'currency', t0.currency, 'status', t0.status, 'issued_at', t0.issued_at, 'due_at', t0.due_at, 'paid_at', t0.paid_at, 'lines', t0.lines, 'payments', t0.payments) AS j, json_build_array(t0.issued_at::text, t0.id::text) AS k, row_number() OVER (ORDER BY t0.issued_at DESC, t0.id DESC) AS rn
  FROM billing.invoice_detail t0
  JOIN page ON page.id = t0.id
  ORDER BY t0.issued_at DESC, t0.id DESC) q

-- ── BillingService.invoice ──
-- $1 = @invoice_id :: bigint
-- $2 = @org_id :: bigint
SELECT q.j::text FROM (SELECT json_build_object('id', t0.id::text, 'org_id', t0.org_id::text, 'number', t0.number, 'amount', t0.amount::text, 'currency', t0.currency, 'status', t0.status, 'issued_at', t0.issued_at, 'due_at', t0.due_at, 'paid_at', t0.paid_at, 'lines', t0.lines, 'payments', t0.payments) AS j
  FROM billing.invoice_detail t0
  WHERE (t0.id = ($1::text)::bigint) AND (t0.org_id = ($2::text)::bigint)
  LIMIT 1) q

-- ── BillingService.retry_payment #1 ──
-- $1 = @org_id :: bigint
-- $2 = InvoiceStatus.open :: billing.invoice_status
SELECT q.j::text FROM (SELECT json_build_object('id', t0.id::text, 'number', t0.number) AS j
  FROM billing.invoices t0
  WHERE (t0.org_id = ($1::text)::bigint) AND (t0.status = ($2::text)::billing.invoice_status)
  ORDER BY t0.due_at, t0.id
  LIMIT 1) q

-- ── BillingService.retry_payment #2 ──
-- $1 = @invoice.id :: bigint
-- $2 = PaymentStatus.failed :: billing.payment_status
SELECT q.j::text FROM (SELECT json_build_object('id', t0.id::text, 'failure_code', t0.failure_code) AS j
  FROM billing.payments t0
  WHERE (t0.invoice_id = ($1::text)::bigint) AND (t0.status = ($2::text)::billing.payment_status)
  ORDER BY t0.created_at DESC, t0.id DESC
  LIMIT 1) q

-- ── BillingService.summary ──
-- $1 = @org_id :: bigint
SELECT q.j::text FROM (SELECT json_build_object('org_id', t0.org_id::text, 'slug', t0.slug, 'invoice_count', t0.invoice_count, 'open_count', t0.open_count, 'paid_total', t0.paid_total::text, 'oldest_due', t0.oldest_due) AS j
  FROM org.org_billing_summary t0
  WHERE t0.org_id = ($1::text)::bigint
  LIMIT 1) q

-- ── OrgService.detail ──
-- $1 = @org_id :: bigint
SELECT q.j::text FROM (SELECT json_build_object('id', t0.id::text, 'slug', t0.slug, 'name', t0.name, 'created_at', t0.created_at, 'members', t0.members) AS j
  FROM org.org_with_members t0
  WHERE t0.id = ($1::text)::bigint
  LIMIT 1) q

-- ── OrgService.members ──
-- $1 = @org_id :: bigint
SELECT coalesce(json_agg(q.j), '[]'::json)::text FROM (SELECT json_build_object('account_id', t0.account_id::text, 'role', t0.role, 'joined_at', t0.joined_at, 'account', CASE WHEN t1.id IS NULL THEN NULL ELSE json_build_object('id', t1.id::text, 'email', t1.email, 'display_name', t1.display_name) END) AS j
  FROM org.members t0
  LEFT JOIN auth.accounts t1 ON t1.id = t0.account_id
  WHERE t0.org_id = ($1::text)::bigint
  ORDER BY t0.joined_at) q

-- ── OrgService.invites ──
-- $1 = @org_id :: bigint
SELECT coalesce(json_agg(q.j), '[]'::json)::text FROM (SELECT json_build_object('id', t0.id::text, 'email', t0.email, 'role', t0.role, 'expires_at', t0.expires_at, 'created_at', t0.created_at) AS j
  FROM org.invites t0
  WHERE (t0.org_id = ($1::text)::bigint) AND (t0.accepted_at IS NULL)
  ORDER BY t0.created_at DESC) q

-- ── OrgService.accept_invite ──
-- $1 = @token_hash :: varchar(64)
-- $2 = date.now() :: timestamptz
SELECT q.j::text FROM (SELECT json_build_object('id', t0.id::text, 'org_id', t0.org_id::text, 'role', t0.role) AS j
  FROM org.invites t0
  WHERE ((t0.token_hash = ($1::text)::varchar(64)) AND (t0.accepted_at IS NULL)) AND (t0.expires_at > ($2::text)::timestamptz)
  LIMIT 1) q

-- ── view SubscriptionDetail ──
SELECT coalesce(json_agg(q.j), '[]'::json)::text FROM (SELECT json_build_object('id', t0.id::text, 'org_id', t0.org_id::text, 'status', t0.status, 'current_period_start', t0.current_period_start, 'current_period_end', t0.current_period_end, 'cancel_at', t0.cancel_at, 'plan', CASE WHEN t1.id IS NULL THEN NULL ELSE json_build_object('id', t1.id::text, 'code', t1.code, 'name', t1.name, 'price', t1.price::text, 'currency', t1.currency, 'interval', t1.interval) END, 'org', CASE WHEN t2.id IS NULL THEN NULL ELSE json_build_object('id', t2.id::text, 'slug', t2.slug, 'name', t2.name) END) AS j
  FROM billing.subscriptions t0
  LEFT JOIN billing.plans t1 ON t1.id = t0.plan_id
  LEFT JOIN org.orgs t2 ON t2.id = t0.org_id) q

-- ── view InvoiceDetail ──
-- $1 = 200 :: int
-- $2 = 20 :: int
SELECT coalesce(json_agg(q.j), '[]'::json)::text FROM (SELECT json_build_object('id', t0.id::text, 'org_id', t0.org_id::text, 'number', t0.number, 'amount', t0.amount::text, 'currency', t0.currency, 'status', t0.status, 'issued_at', t0.issued_at, 'due_at', t0.due_at, 'paid_at', t0.paid_at, 'lines', coalesce(t1_agg.data, '[]'::json), 'payments', coalesce(t2_agg.data, '[]'::json)) AS j
  FROM billing.invoices t0
  LEFT JOIN LATERAL (
      SELECT coalesce(json_agg(c.j), '[]'::json) AS data
        FROM (SELECT json_build_object('id', t1.id::text, 'description', t1.description, 'quantity', t1.quantity, 'unit_price', t1.unit_price::text) AS j
        FROM billing.invoice_lines t1
        WHERE t1.invoice_id = t0.id
        ORDER BY t1.id
        LIMIT ($1::text)::int) c
  ) t1_agg ON true
  LEFT JOIN LATERAL (
      SELECT coalesce(json_agg(c.j), '[]'::json) AS data
        FROM (SELECT json_build_object('id', t2.id::text, 'provider', t2.provider, 'provider_ref', t2.provider_ref, 'amount', t2.amount::text, 'status', t2.status, 'created_at', t2.created_at) AS j
        FROM billing.payments t2
        WHERE t2.invoice_id = t0.id
        ORDER BY t2.created_at DESC
        LIMIT ($2::text)::int) c
  ) t2_agg ON true) q

-- ── view OrgBillingSummary ──
-- $1 = InvoiceStatus.open :: billing.invoice_status
-- $2 = InvoiceStatus.paid :: billing.invoice_status
-- $3 = InvoiceStatus.open :: billing.invoice_status
SELECT coalesce(json_agg(q.j), '[]'::json)::text FROM (SELECT json_build_object('org_id', t0.id::text, 'slug', t0.slug, 'invoice_count', count(t1.id)::int, 'open_count', (count(t1.id) FILTER (WHERE t1.status = ($1::text)::billing.invoice_status))::int, 'paid_total', (sum(t1.amount) FILTER (WHERE t1.status = ($2::text)::billing.invoice_status))::text, 'oldest_due', min(t1.due_at) FILTER (WHERE t1.status = ($3::text)::billing.invoice_status)) AS j
  FROM org.orgs t0
  LEFT JOIN billing.invoices t1 ON t1.org_id = t0.id
  GROUP BY t0.id, t0.slug) q

-- ── view OrgWithMembers ──
-- $1 = 200 :: int
SELECT coalesce(json_agg(q.j), '[]'::json)::text FROM (SELECT json_build_object('id', t0.id::text, 'slug', t0.slug, 'name', t0.name, 'created_at', t0.created_at, 'members', coalesce(t1_agg.data, '[]'::json)) AS j
  FROM org.orgs t0
  LEFT JOIN LATERAL (
      SELECT coalesce(json_agg(c.j), '[]'::json) AS data
        FROM (SELECT json_build_object('role', t1.role, 'joined_at', t1.joined_at, 'account', CASE WHEN t2.id IS NULL THEN NULL ELSE json_build_object('id', t2.id::text, 'email', t2.email, 'display_name', t2.display_name) END) AS j
        FROM org.members t1
        LEFT JOIN auth.accounts t2 ON t2.id = t1.account_id
        WHERE t1.org_id = t0.id
        ORDER BY t1.joined_at
        LIMIT ($1::text)::int) c
  ) t1_agg ON true) q

-- ── view MemberAccess ──
SELECT coalesce(json_agg(q.j), '[]'::json)::text FROM (SELECT json_build_object('org_id', t0.org_id::text, 'account_id', t0.account_id::text, 'role', t0.role, 'org', CASE WHEN t1.id IS NULL THEN NULL ELSE json_build_object('id', t1.id::text, 'slug', t1.slug, 'name', t1.name) END) AS j
  FROM org.members t0
  LEFT JOIN org.orgs t1 ON t1.id = t0.org_id) q
